version: "3"

services:
  registry:
    container_name: asta-registry # Name of the service
    image: registry:2.8.2 # Image of the service
    restart: always
    ports:
      - "5500:5000" # Port mapping => host:container
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "['https://registry-ui.astalife.co']" # Replace with your registry UI URL
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "[Authorization,Accept,Cache-Control]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "[HEAD,GET,OPTIONS,DELETE]"
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: "[Docker-Content-Digest]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: "[true]"
    volumes:
      - registry-data:/var/lib/registry # Volume mapping => host:container

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 8500:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Asta Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - CATALOG_ELEMENTS_LIMIT=1000
      - REGISTRY_URL=https://registry.astalife.co # Replace with your registry URL
      - REGISTRY_SECURED=true # Enable secured mode
      - REGISTRY_AUTH=basic # Use Basic Authentication
      - REGISTRY_USER=user-name # Replace with your username
      - REGISTRY_PASS=password # Replace with your password
    container_name: asta-registry-ui
    depends_on:
      - registry

volumes:
  registry-data:
